
obj_short_to_long = {'handtowelholder': 'hand towel holder',
                     'toiletpaperhanger': 'toilet paper hanger',
                     'toiletpaper': 'toilet paper',
                     'diningtable': 'dining table',
                     'glassbottle': 'glass bottle',
                     'butterknife': 'butter knife',
                     'spraybottle': 'spray bottle',
                     'tennisracket': 'tennis racket',
                     'floorlamp': 'floor lamp',
                     'tissuebox': 'tissue box',
                     'garbagecan': 'garbage can',
                     'bathtubbasin': 'bathtub basin',
                     'alarmclock': 'alarm clock',
                     'winebottle': 'wine bottle',
                     'coffeetable': 'coffee table',
                     'desklamp': 'desk lamp',
                     'stoveburner': 'stove burner',
                     'remotecontrol': 'remote control',
                     'dishsponge': 'dish sponge',
                     'handtowel': 'hand towel',
                     'wateringcan': 'watering can',
                     'baseballbat': 'baseball bat',
                     'creditcard': 'credit card',
                     'saltshaker': 'salt shaker',
                     'soapbottle': 'soap bottle',
                     'sidetable': 'side table',
                     'peppershaker': 'pepper shaker',
                     'coffeemachine': 'coffee machine',
                     'teddybear': 'teddy bear',
                     'candle': 'candle',
                     'knife': 'knife',
                     'cd': 'cd',
                     'apple': 'apple',
                     'fridge': 'fridge',
                     'pot': 'pot',
                     'drawer': 'drawer',
                     'pencil': 'pencil',
                     'pillow': 'pillow',
                     'mug': 'mug',
                     'safe': 'safe',
                     'desk': 'desk',
                     'laptop': 'laptop',
                     'plate': 'plate',
                     'cup': 'cup',
                     'fork': 'fork',
                     'sinkbasin': 'sink',
                     'pen': 'pen',
                     'bowl': 'bowl',
                     'tomato': 'tomato',
                     'dresser': 'dresser',
                     'statue': 'statue',
                     'basketball': 'basketball',
                     'kettle': 'kettle',
                     'microwave': 'microwave',
                     'spoon': 'spoon',
                     'cabinet': 'cabinet',
                     'book': 'book',
                     'shelf': 'shelf',
                     'cart': 'cart',
                     'box': 'box',
                     'keychain': 'keychain',
                     'bread': 'bread',
                     'armchair': 'armchair',
                     'newspaper': 'newspaper',
                     'bed': 'bed',
                     'pan': 'pan',
                     'lettuce': 'lettuce',
                     'watch': 'watch',
                     'cellphone': 'cellphone',
                     'cloth': 'cloth',
                     'potato': 'potato',
                     'spatula': 'spatula',
                     'plunger': 'plunger',
                     'egg': 'egg',
                     'ladle': 'ladle',
                     'sofa': 'sofa',
                     'soapbar': 'soapbar',
                     'vase': 'vase',
                     'ottoman': 'ottoman',
                     'toilet': 'toilet',
                     'countertop': 'countertop'}

obj_long_to_short = {'hand towel holder': 'handtowelholder',
                     'toilet paper hanger': 'toiletpaperhanger',
                     'toilet paper': 'toiletpaper',
                     'dining table': 'diningtable',
                     'glass bottle': 'glassbottle',
                     'butter knife': 'butterknife',
                     'spray bottle': 'spraybottle',
                     'tennis racket': 'tennisracket',
                     'floor lamp': 'floorlamp',
                     'tissue box': 'tissuebox',
                     'garbage can': 'garbagecan',
                     'bathtub basin': 'bathtubbasin',
                     'alarm clock': 'alarmclock',
                     'wine bottle': 'winebottle',
                     'coffee table': 'coffeetable',
                     'desk lamp': 'desklamp',
                     'stove burner': 'stoveburner',
                     'remote control': 'remotecontrol',
                     'dish sponge': 'dishsponge',
                     'hand towel': 'handtowel',
                     'watering can': 'wateringcan',
                     'baseball bat': 'baseballbat',
                     'credit card': 'creditcard',
                     'salt shaker': 'saltshaker',
                     'soap bottle': 'soapbottle',
                     'side table': 'sidetable',
                     'pepper shaker': 'peppershaker',
                     'coffee machine': 'coffeemachine',
                     'teddy bear': 'teddybear',
                     'candle': 'candle',
                     'knife': 'knife',
                     'cd': 'cd',
                     'apple': 'apple',
                     'fridge': 'fridge',
                     'pot': 'pot',
                     'drawer': 'drawer',
                     'pencil': 'pencil',
                     'pillow': 'pillow',
                     'mug': 'mug',
                     'safe': 'safe',
                     'desk': 'desk',
                     'laptop': 'laptop',
                     'plate': 'plate',
                     'cup': 'cup',
                     'fork': 'fork',
                     'sink': 'sinkbasin',
                     'pen': 'pen',
                     'bowl': 'bowl',
                     'tomato': 'tomato',
                     'dresser': 'dresser',
                     'statue': 'statue',
                     'basketball': 'basketball',
                     'kettle': 'kettle',
                     'microwave': 'microwave',
                     'spoon': 'spoon',
                     'cabinet': 'cabinet',
                     'book': 'book',
                     'shelf': 'shelf',
                     'cart': 'cart',
                     'box': 'box',
                     'keychain': 'keychain',
                     'bread': 'bread',
                     'armchair': 'armchair',
                     'newspaper': 'newspaper',
                     'bed': 'bed',
                     'pan': 'pan',
                     'lettuce': 'lettuce',
                     'watch': 'watch',
                     'cellphone': 'cellphone',
                     'cloth': 'cloth',
                     'potato': 'potato',
                     'spatula': 'spatula',
                     'plunger': 'plunger',
                     'egg': 'egg',
                     'ladle': 'ladle',
                     'sofa': 'sofa',
                     'soapbar': 'soapbar',
                     'vase': 'vase',
                     'ottoman': 'ottoman',
                     'toilet': 'toilet',
                     'countertop': 'countertop'}

goal_long_to_short = {'robot_has_obj': 'has',
                      'toggled': 'toggle',
                      'cleaned': 'clean',

                      'sliced': 'sliced',
                      'on': 'on',
                      'cold': 'cold',
                      'hot': 'hot'
                      }

goal_short_to_long = {'has': 'robot_has_obj',
                      'toggle': 'toggled',
                      'clean': 'cleaned',

                      'sliced': 'sliced',
                      'on': 'on',
                      'cold': 'cold',
                      'hot': 'hot'
                      }
